FROM ubuntu:26.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        cmake \
        gcc-13 \
        g++-13 \
        git \
        make \
        libc6-dev \
        libsqlite3-dev \
        libboost-dev \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100 \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /src
